import 'package:flutter/material.dart';
import 'package:skeletonizer/src/rendering/render_skeleton_shader_mask.dart';

/// Builds a [RenderSkeletonShaderMask]
class SkeletonShaderMask extends SingleChildRenderObjectWidget {
  /// Creates a widget that applies a mask generated by a [Shader] to its child.
  ///
  /// The [shader] and [blendMode] arguments must not be null.
  const SkeletonShaderMask({
    super.key,
    super.child,
  });

  @override
  RenderSkeletonShaderMask createRenderObject(BuildContext context) {
    return RenderSkeletonShaderMask();
  }
}
